# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_Confd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=40, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('project_url', models.CharField(max_length=40, verbose_name='\u9879\u76ee\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='vhosts_Confd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vhosts_url', models.CharField(max_length=40, verbose_name='\u5b50\u9879\u76ee\u8def\u5f84')),
                ('server_name', models.CharField(max_length=40, verbose_name='\u57df\u540d')),
                ('server_root', models.CharField(max_length=40, verbose_name='\u7a0b\u5e8f\u76ee\u5f55')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confd.project_Confd', verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
        migrations.DeleteModel(
            name='Confd',
        ),
    ]
