# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0003_auto_20180612_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_confd',
            name='project_url',
            field=models.CharField(max_length=40, verbose_name='\u9879\u76ee\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='vhosts_confd',
            name='vhosts_url',
            field=models.CharField(max_length=40, verbose_name='\u5b50\u9879\u76ee\u8def\u5f84'),
        ),
    ]
