# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0004_auto_20180612_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vhosts_confd',
            old_name='vhosts_url',
            new_name='vhosts_key',
        ),
        migrations.RenameField(
            model_name='vhosts_confd',
            old_name='server_root',
            new_name='vhosts_value',
        ),
        migrations.RemoveField(
            model_name='vhosts_confd',
            name='server_name',
        ),
    ]
