# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0005_auto_20180612_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhosts_confd',
            name='vhosts_key',
            field=models.CharField(max_length=40, unique=True, verbose_name='\u5b50\u9879\u76ee\u8def\u5f84'),
        ),
    ]
