# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confd', '0006_auto_20180612_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhosts_confd',
            name='vhosts_status',
            field=models.IntegerField(choices=[(0, 'UP'), (1, 'Down')], default=0, verbose_name='\u5de5\u5355\u72b6\u6001'),
        ),
    ]
